### PR TITLE
_compression: Fix uninitialized logger

### PR DESCRIPTION
**Pull request by mckelvin**
While importing arctic, a warning message `No handlers could be found for logger "arctic._compression"` will occur, which is quite annoying. I checked the code and found it's caused by calling `logger.warning` before `setup_logging()`. To avoid this behaviour, I guess it's a better choice to import clz4 lazily.

### CODE REVIEW

**Comment by jamesblackburn** [comment]
It looks like this is in the exception handler path for the import.  Is this only happening because that `.so` isn't building for you? I would have thought that as we use logging in lots of places this might be a general problem?

**Comment by mckelvin** [comment]
> It looks like this is in the exception handler path for the import. Is this only happening because that .so isn't building for you? 

This happens to me when using arctic in Ubuntu 14.04. The arctic is built in [wheel](http://pythonwheels.com) from a [python:2.7.12 docker image](https://hub.docker.com/_/python/).

```
$ python -c "import arctic._compress"
No handlers could be found for logger "arctic._compression"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /vagrant/projects/hom/venv/local/lib/python2.7/site-packages/arctic/_compress.so)
```

Actually that's not a big deal and I'd like to ignore the broken `_compress.so` since it will fallback to use `lz4`.

* * *

> I would have thought that as we use logging in lots of places this might be a general problem?

Agree but I'd appreciate it if we can take control of what writes to stderr.

**Comment by mckelvin** [comment]
> so you're importing arctic before you've setup your logger

Yes. Calling `setup_logging` in a main function should be a better choice. And that's exactly the way how `setup_logging` is use in [scripts/arctic_init_library](https://github.com/manahl/arctic/blob/6d4acca/arctic/scripts/arctic_init_library.py#L21).

**Comment by jamesblackburn** [comment]
ok it sounds like w're in agreement @mckelvin 

I'd rather not make this lazy as:
 - users should have a logger configured when using this library
 - we expect this `.so` to be built and exist for our users
 - the additional code does increase the complexity in this module

**Comment by mckelvin** [comment]
@jamesblackburn Thanks for your response. 

> the additional code does increase the complexity in this module

Agree.

> we expect this .so to be built and exist for our users

Agree. But if it's not existed, user should be warned with detailed message instead of `No handlers could be found for logger "arctic._compression"`, which is meaningless if he doesn't inspect the code. 

**May be we can use [`warnings`](https://docs.python.org/2/library/warnings.html) module to show this message ?**

> users should have a logger configured when using this library

Users should configure in the beginning of `main()`, just like what https://github.com/manahl/arctic/blob/6e1f0fe/arctic/scripts/arctic_copy_data.py#L65 does. But this warning happened in import-time. The user have to write dirty code like:

```python
import foo
import bar
import logging
logging.basicConfig(...)  ## calling this at import-time
import arctic

def naive(...):
    ...

def main():
    ...

...
``` 

So, I think use `warnings` should be a better idea. What do you think @jamesblackburn ?

**Pull request closed without merging**
