### PR TITLE
Force lz4 on to 0.8.2

### PR DESCRIPTION
**Pull request by bmoscon**

### CODE REVIEW

**Comment by bmoscon** [comment]
we'll probably want to change arctic so it will work with the latest version of lz4, but for now, lets just fix the build error

**Comment by jamesblackburn** [comment]
So I think we're seeing an error caused by version (/symbol) mismatch between python-lz4 0.8.2 and the source code in the arctic library.  In our env we're getting this during pytest setup

```
==================================== ERRORS ====================================
______________________________ ERROR collecting  _______________________________
py-1.4.31-py2.7.egg/py/_path/common.py:332: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
py-1.4.31-py2.7.egg/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
py-1.4.31-py2.7.egg/py/_path/common.py:368: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
pytest-2.9.2-py2.7.egg/_pytest/main.py:647: in _recurse
    ihook = self.gethookproxy(path)
pytest-2.9.2-py2.7.egg/_pytest/main.py:550: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
pytest-2.9.2-py2.7.egg/_pytest/config.py:297: in _getconftestmodules
    mod = self._importconftest(conftestpath)
pytest-2.9.2-py2.7.egg/_pytest/config.py:333: in _importconftest
    self.consider_conftest(mod)
pytest-2.9.2-py2.7.egg/_pytest/config.py:357: in consider_conftest
    self.consider_module(conftestmodule)
pytest-2.9.2-py2.7.egg/_pytest/config.py:363: in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", None))
pytest-2.9.2-py2.7.egg/_pytest/config.py:370: in _import_plugin_specs
    self.import_plugin(import_spec)
pytest-2.9.2-py2.7.egg/_pytest/config.py:392: in import_plugin
    raise new_exc
E   ImportError: Error importing plugin "arctic.fixtures.arctic": /ahljenkins/slave/build/workspace/DATA/arctic/venv/lib/python2.7/site-packages/lz4-0.8.2-py2.7-linux-x86_64.egg/lz4.so: undefined symbol: LZ4_compress_fast
```

**Comment by jamesblackburn** [comment]
CC @dimosped

**Comment by bmoscon** [comment]
@jamesblackburn @dimosped if 0.8.2 is the problem, we can pin to any version of lz4 we want (just not the latest). 0.8.2 is nearly a year old. What version of lz4 is in the local env?

**Comment by dimosped** [comment]
the last good build used 0.7.0: https://pypi.python.org/pypi/lz4/0.7.0
2014-07-07 build

**Comment by bmoscon** [comment]
ok, we can change the pin to <= 0.8.2 so that 0.7.0 in the local pydev will still work ok. @jamesblackburn @dimosped

**Comment by dimosped** [comment]
I think the issue is that in python-lz4 0.8.0 they added a system-level dependency for many symbols.
So the python lz4 so uses Linux's standard lib path to fetch liblz4.so.1, which leads to inconsistent build results depending on the local machine installation:

$ ldd /users/is/dpediaditakis/git/arctic/venv/lib/python2.7/site-packages/lz4-0.8.2-py2.7-linux-x86_64.egg/lz4.so 
        linux-vdso.so.1 =>  (0x00007fffe41fd000)
        **liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00002ae92006c000)**
        libpython2.7.so.1.0 => /opt/ahl/releases/python/2.7.3/lib64/libpython2.7.so.1.0 (0x00002ae92027a000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ae92062b000)
        libc.so.6 => /lib64/libc.so.6 (0x00002ae920847000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002ae920ba1000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00002ae920da5000)
        libm.so.6 => /lib64/libm.so.6 (0x00002ae920fa8000)
        /lib64/ld-linux-x86-64.so.2 (0x00000038d2c00000)
(venv)[cn90] ~/git/arctic

$ ldd /users/is/dpediaditakis/git/arctic/venv2/lib/python2.7/site-packages/lz4-0.7.0-py2.7-linux-x86_64.egg/lz4.so 
        linux-vdso.so.1 =>  (0x00007fff2a1b2000)
        libpython2.7.so.1.0 => /opt/ahl/releases/python/2.7.3/lib64/libpython2.7.so.1.0 (0x00002b073c119000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b073c4cb000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b073c6e7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b073ca40000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00002b073cc45000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b073ce48000)
        /lib64/ld-linux-x86-64.so.2 (0x00000038d2c00000)

**Pull request merged**
