### PR TITLE
Fix column naming issue #113

### PR DESCRIPTION
**Pull request by bmoscon**
@TomTaylorLondon indicated this has been an issue for him in the past, so I've created a fix for #113 

Because the dtype operations in the record conversions require a string for the record name, I opted to use a "magic number" (string in this case) to indicate we've converted to a string from an integer (or a None). I'm open to other methods to fix this.

### CODE REVIEW

**Comment by bmoscon** [comment]
@TomTaylorLondon 
@jamesblackburn 
@richardbounds

**Comment by richardbounds** [comment]
It isn't a big change, and it looks OK but I'm not convinced it is necessary - I don't think it is unreasonable to insist on naming the columns - we don't necessarily have to persist the entire universe of possible dataframes perfectly.

**Comment by bmoscon** [comment]
@richardbounds im inclined to agree with you. @TomTaylorLondon mentioned it had been an issue for him in the past and asked me to fix it, so I'll let him argue the merits :)

**Comment by TomTaylorLondon** [comment]
@bmoscon @richardbounds I think it's useful to fix this - it's not a corner case to have un-labeled data-frames. Could you also handle the case when the index isn't named:

https://github.com/manahl/arctic/blob/master/arctic/store/_pandas_ndarray_store.py#L57

**Comment by richardbounds** [comment]
How is it not a corner case? When is it a good idea to have unlabelled dataframes?

**Comment by TomTaylorLondon** [comment]
@richardbounds I think it would be good to fix - it's not critical but we have plenty of tests, nodes in graphs etc. where it would have been helpful. Do you think strongly enough about this to not merge the request?

**Comment by bmoscon** [comment]
@richardbounds per a conversation with @TomTaylorLondon I'm going to scrap this and just emit a long line when we convert any names. That ok with you?

**Comment by richardbounds** [comment]
Fine by me.

**Pull request closed without merging**
