### PR TITLE
Black formatting v2

### PR DESCRIPTION
**Pull request by shashank88**
As @jamesblackburn suggested I have skipped the string normalization for now and changed to 120. Have only formatted src files for now and not tests as that requires more work eg. Moving stuff to data etc.

### CODE REVIEW

**Comment by bmoscon** [comment]
I'll refrain from reviewing because I'm kind of anti-black. Line like this to me invalidate the argument that this formatting makes things better or easier to read. Its a personal choice 🤷‍♂ 
https://github.com/manahl/arctic/pull/778/files#diff-63f2797d12f7fd46e9c8345736f1ac36R37

**Comment by shashank88** [comment]
> I'll refrain from reviewing because I'm kind of anti-black. Line like this to me invalidate the argument that this formatting makes things better or easier to read. Its a personal choice 🤷‍♂
> https://github.com/manahl/arctic/pull/778/files#diff-63f2797d12f7fd46e9c8345736f1ac36R37

In my last place, we had the same rules as the formatting rule you pointed to. Basically, if something goes multiline you split each argument to a separate line. That's the thing with autoformatters, that no 2 people will fully agree with the end result but the end goal is to be good enough and save time in the long term. gofmt was something I loved when I did some Golang, even though I didn't agree with some of the formattings it did as everyone did the same thing

**Comment by bmoscon** [comment]
true. I actually happen to like go's formatting. Thats part of the language standard though, black is not

**Comment by shashank88** [comment]
This is funny. pycodestyle check failed after running black formatting. Did not expect this 😆

**Comment by yschimke** [comment]
Would we disable that, if we use black?

**Comment by shashank88** [comment]
> Would we disable that, if we use black?

We shouldn't have to. pycodestyle is the python standard pep8 checker and black is supposed to be compatible with pep8. Will take a look later today.

**Comment by shashank88** [comment]
Closing this. Will recreate a PR after reverting forward pointers.

**Pull request closed without merging**
