### PR TITLE
Fix issue #712 - pandas deprecation warning in chunkstore serializer

### PR DESCRIPTION
**Pull request by bmoscon**
Fixes issue #712

### CODE REVIEW

**Comment by yschimke** [comment]
Change looks good based on old behaviour and new

https://pandas.pydata.org/pandas-docs/version/0.20/generated/pandas.api.types.infer_dtype.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.types.infer_dtype.html

Should we plan to change to the new behaviour (skipnan=True) in the future in a separate PR?

**Comment by shashank88** [comment]
Looks good. Is there something that's different in py3? 
`E   AssertionError: DataFrame.columns are different
E   
E   DataFrame.columns values are different (66.66667 %)
E   [left]:  Index(['a', 'b', 'c'], dtype='object')
E   [right]: Index(['c', 'b', 'a'], dtype='object')
`

**Comment by bmoscon** [comment]
@yschimke I'd have to check how setting it to true changed the behavior the code block its in (if it even would). It may be fine to change.

**Comment by bmoscon** [comment]
@shashank88 thats one of the random things that seems to only happen on travis...

**Comment by shashank88** [comment]
> @shashank88 thats one of the random things that seems to only happen on travis...

Ahh ... cool then

**Pull request merged**
