### PR TITLE
No longer require cython to be pre-installed

### PR DESCRIPTION
**Pull request by bmoscon**
see issue #382

### CODE REVIEW

**Comment by bmoscon** [comment]
@jamesblackburn this finally fixes a very vexing issue - requiring cython to be pre-installed before building arctic!

**Comment by bmoscon** [comment]
also note it does require setuptools 18.0+, but considering that were on version 36.1.0, I don't think this is a major issue. Its certainly no worse than requiring users manually install cython before building arctic.

**Comment by jamesblackburn** [comment]
This does look neat. Unfortunately this doesn't work in our legacy Python environment (which has an ancient setuptools :( :( ).

Is there any easy way for us to keep building against older setuptools if this goes in?

**Comment by bmoscon** [comment]
@jamesblackburn yes its possible to support old + new setuptools. Let me make them change and I'll ping you to re-review

**Comment by jamesblackburn** [comment]
Ok, thanks.  Currently getting:

```
+ python setup.py develop
warning: easy_install: byte-compiling is disabled, skipping.

warning: easy_install: byte-compiling is disabled, skipping.

running develop
running egg_info
creating arctic.egg-info
writing requirements to arctic.egg-info/requires.txt
writing arctic.egg-info/PKG-INFO
writing top-level names to arctic.egg-info/top_level.txt
writing dependency_links to arctic.egg-info/dependency_links.txt
writing entry points to arctic.egg-info/entry_points.txt
writing manifest file 'arctic.egg-info/SOURCES.txt'
writing manifest file 'arctic.egg-info/SOURCES.txt'
running build_ext
building 'arctic._compress' extension
error: unknown file type '.pyx' (from 'src/_compress.pyx')
Build step 'Execute shell' marked build as failure
Set build name.
New build name is '#811-origin/cython-dep'
Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: '#811-origin/cython-dep', new value: '#811-origin/cython-dep'
Skipping Cobertura coverage report as build was not UNSTABLE or better ...
Recording test results
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
[SLOCCount] Skipping results publication since the build is not successful
```

**Comment by achamayou** [comment]
Ran into this earlier, it can be fixed by callling cythonize on the list of
files inside setup.py. Will follow up with an example.

**Comment by bmoscon** [comment]
alright @jamesblackburn give this one a try and let me know if it works on your old version of setuptools. It defers the actual import / cythonization until after setuptools has done the install of cython.

**Comment by bmoscon** [comment]
@jamesblackburn ping

**Pull request merged**
