### PR TITLE
Raise if appending out-of-order items; Add concat flag

### PR DESCRIPTION
**Pull request by AdrianTeng**
This function exists since 2014 internally (originally by @TomTaylorLondon). Porting this to open source world.

### CODE REVIEW

**Comment by AdrianTeng** [comment]
@bmoscon done

**Comment by bmoscon** [comment]
looks good, thanks!

**Comment by bmoscon** [comment]
:shipit:

**Comment by AdrianTeng** [comment]
Travis seems to be occasionally killing  the build due to no output for 10mins -> timeout?

**Comment by bmoscon** [comment]
@AdrianTeng yes thats some weird artifact that happened when we moved over to the AHL mongo pytest fixture. Not sure why . . . :(

**Pull request merged**
