### PR TITLE
Add upsert to Append in ChunkStore

### PR DESCRIPTION
**Pull request by bmoscon**
Add upsert to append in chunkstore. Default is false, so it wont break anything and is backwards compatible.

### CODE REVIEW

**Comment by bmoscon** [comment]
would like to get this in before the next release :)

**Comment by bmoscon** [comment]
@dimosped @jamesblackburn

**Comment by dimosped** [comment]
looks good @bmoscon 
I'll merge it.

**Comment by bmoscon** [comment]
thanks @dimosped

**Pull request merged**
