### PR TITLE
Support for audit logs in ChunkStore

### PR DESCRIPTION
**Pull request by bmoscon**
Enable audit logs on operations with the audit keyword arg. Writes supplied dict along with additional information into the audit collection

### CODE REVIEW

**Comment by bmoscon** [comment]
see #320

**Comment by bmoscon** [comment]
@jamesblackburn

**Comment by jamesblackburn** [comment]
Auditing in the version store provides the ability to preserve the data before and after the change.  It looks like here there's an audit log, but no actual history of the change being made?

**Comment by bmoscon** [comment]
Version store is a different case - the data is never "gone" we mainly want to see what operations took place and what the state was at that time (chunks, appended rows, etc)

**Pull request merged**
