### PR TITLE
Issue #313 User Defined Metadata

### PR DESCRIPTION
**Pull request by bmoscon**
Set and read user defined per-symbol metadata

### CODE REVIEW

**Comment by bmoscon** [comment]
@jamesblackburn take a look

**Comment by bmoscon** [comment]
@jlou2u

**Comment by jlou2u** [comment]
worth adding a test that hits the segmenting code to make sure it works as we'd like?

**Comment by jlou2u** [comment]
What about adding a test with unserializable data in the user metadata.  The intent would be to make sure the cause of exception is clear and understandable for a user.

**Comment by jamesblackburn** [comment]
Do you really need metadata per chunk rather than metadata per symbol?  In VersionStore (and in general) we store metadata per symbol - I'm not sure how useful it is to have this per chunk...

**Comment by bmoscon** [comment]
@jlou2u metadata collection is per chunk, not per segment, so no reason to test that. would be good to put in some clearer exceptions around bad metadata.

**Comment by bmoscon** [comment]
@jamesblackburn i suppose we really want a way to do both, but currently only have a need for per chunk

**Comment by bmoscon** [comment]
@jamesblackburn spoke with justin, we're going to change this around a bit, so I'll let you know when its ready

**Pull request merged**
