### PR TITLE
fix tickstore unicode handling, support both unicode and utf-8 arrays.

### LINKED ISSUE #539: tickstore unicode support fix
https://github.com/manahl/arctic/blob/c0e9e68b55920f37563763029613fe934919cd45/arctic/tickstore/tickstore.py#L646-L647

These two lines were supposed to transform a `utf-8` array to a `unicode` array. 

Two problems here:

1. if array was encoded in `utf-8`, `s.decode('utf-8')` should be used instead of `s.encode('utf-8')`.
2. if array was itself a `unicode` array , the first line should not be executed.

### PR DESCRIPTION
**Pull request by tujian**
fix #539

### CODE REVIEW

**Comment by bmoscon** [comment]
@tujian please add some unit tests that illustrate the fix

**Comment by tujian** [comment]
Sorry for the late reply. I think all tests in `test_ts_read` passed. Please review the fix.

**Comment by tujian** [comment]
Anything else I can do for this? Please review the commits and provide some guidance. : ) @jamesblackburn @bmoscon

**Comment by tujian** [comment]
Commits rebased and tests passed on travis. Please review the PR.

**Comment by bmoscon** [comment]
@jamesblackburn changes look good. Take a look please!

**Comment by bmoscon** [comment]
@jamesblackburn any opposition to merging this in?

**Comment by dimosped** [comment]
@bmoscon @tujian  I wonder if we can add a line in CHANGES.md about the fix

**Comment by bmoscon** [comment]
@dimosped it took us 4 months to even get it all approved and merged in, I'd feel bad if we delayed it for a changes.md file. I merged it and manually updated the changes file

**Comment by tujian** [comment]
My bad. Just came across this.  @bmoscon Thanks for you help!

**Comment by dimosped** [comment]
@bmoscon agreed, thanks

**Pull request merged**
