### PR TITLE
Fixed small bug in DateRange.intersection

### PR DESCRIPTION
**Pull request by davidduenas3**
'DateRange.intersection' method returns CLOSED interval when intersecting ranges with same start[,end] and distinct interval values. 
It should return an  OPEN_*(>start) interval as it is subset of the same CLOSED_*(>=start)

### CODE REVIEW

**Comment by bmoscon** [comment]
@davidduenas3 thanks for this! Can you add some new unit tests that pertain to this?

**Comment by bmoscon** [comment]
@davidduenas3 thanks! Can you please add some unit tests that pertain to the fix?

**Comment by davidduenas3** [comment]
`oo=DateRange('20110101', '20110102', OPEN_OPEN)
cc=DateRange('20110101', '20110102', CLOSED_CLOSED)
oo.start in oo == False
oo.start in cc == True
oo.start in cc.intersection(oo) == False`
Returns: True, True, True

**Comment by bmoscon** [comment]
@dimosped @jamesblackburn looks good to me, any reason we shouldnt merge this?

**Comment by dimosped** [comment]
@bmoscon  looks good :+1:  thanks

**Comment by dimosped** [comment]
@bmoscon  if no objections, I will add a changelog update and merge and add it in our next (soon to be done) release

**Pull request merged**
