### PR TITLE
Chunkstore SHA Index

### PR DESCRIPTION
**Pull request by bmoscon**
see issue #166 for complete details.

### CODE REVIEW

**Comment by bmoscon** [comment]
@jamesblackburn take a look and let me know

**Comment by jamesblackburn** [comment]
Don't we query on (symbol, sha) when we cleanup old chunks?  I wouldn't think we would need an additional index here...

**Comment by bmoscon** [comment]
@jamesblackburn check out:

https://github.com/manahl/arctic/blob/master/arctic/chunkstore/chunkstore.py#L222

we query just on SHA's to remove old chunks that are no longer used. No reason why I couldn't query on symbol / sha, but also no reason why I can't add a new index,  right?

**Comment by jamesblackburn** [comment]
It's just another index to maintain on each chunk write.  

We previously found that `'sha': {'$in': list(previous_shas)` is also quite slow, so adding the symbol in there will likely help (as the number of SHAs in the sub btree is smaller).

**Comment by bmoscon** [comment]
ok, will change it.

**Comment by bmoscon** [comment]
@jamesblackburn take a look now

**Comment by jamesblackburn** [comment]
+1

**Pull request merged**
