### PR TITLE
Quick stab at handling Apples default gcc (clang) compiler incompatibility

### PR DESCRIPTION
**Pull request by joshuaostrom**
So perhaps simple update to the ReadMe.MD will suffice.  The default gcc compiler on OSX (clang) doesn't support openmp and won't fly.  This PR not-so-elegantly detects when this compiler is in use and issues a warning

`Apple LLVM detected you many need to install (non clang) gcc`

If gcc-\* is found, it will instead use that.  

Alternatives would be 
1) Do nothing, expect OSX users to not have their gcc pointing to the Apple supplied one.
2) Updated Readme.md with note for Apple devs `CC=gcc-4.2 pip install` etc 

No worries if you trash the PR, if some part of it proves useful, great.

### CODE REVIEW

**Comment by AdrianTeng** [comment]
I'm neutral on whether we should change `setup.py` xor `README.md`. @jamesblackburn @Wilfred?

**Comment by Wilfred** [comment]
Aha, we're using OpenMP for the `cython.parallel` stuff (I was initially expecting to see openmp pragmas like `#pragma omp parallel` but it's only used through cython).

I certainly think we should do something to help out apple users. Putting a note in readme.md would be a reasonable approach, as would this patch. However, recent clang versions do support openmp. Apple's LLVM will probably have this in the future, so we ought to have a version check too.

@jamesblackburn I presume you're developing this on a mac? How are you handling this?

**Comment by Wilfred** [comment]
In principle, it should be possible to use OpenMP with the system compiler on Apple: http://stackoverflow.com/a/36000632/509706

**Comment by jamesblackburn** [comment]
The way I've built this before on MacOS is using conda and the gcc that comes with it. I hacked the cython link line to add `-static` to statically link against the openmp .a. The resulting .so then runs, passes the tests and appears to be relocatable.

**Comment by bmoscon** [comment]
not sure what happened when you updated your fork, but now its near impossible to tell the changes you made vs the changes made since you forked . . .

**Comment by joshuaostrom** [comment]
@bmoscon sorry about that, had updated the fork with the latest from arctic's master.  Should be all set now.  (Been tracking down some oddities I'm only seeing when running arctic from within a docker container).

**Comment by bmoscon** [comment]
@joshuaostrom you'll probably need to update your branch/fork to get the build to pass. I'll test it out this weekend and try building a wheel.

**Comment by bmoscon** [comment]
macOS now supported, so closing this.

**Pull request closed without merging**
