### PR TITLE
Version Fixes and new travis setup

### PR DESCRIPTION
**Pull request by bmoscon**
* Fixes pandas compatibility issues
* Removes reserved word from package name
* Updates travis to use an older version of pandas (0.22.0) for python 2.7 tests

### CODE REVIEW

**Comment by bmoscon** [comment]
@shashank88 setting pandas to 0.22.0 for python2.7 seems to break several things. Not sure if we want to support a version that old or not (or older?).

**Comment by yschimke** [comment]
@bmoscon happy to defer decision to you 3, but as an open source maintainer, people wanting newer versions of Arctic probably want newer version of pandas (or should be tolerant of it).

v0.22.0 (December 29, 2017)

**Comment by bmoscon** [comment]
@yschimke I agree 100%. I'm fine saying anything older than 0.23.0 may or may not work (i.e. unsupported). The fact that @shashank88 opened this ticket makes me think that some may still be on ancient versions of pandas: https://github.com/manahl/arctic/issues/725 ;)

**Comment by shashank88** [comment]
@bmoscon yeah, internally we are using pandas 0.22.0 from the build logs which is also a requirement for the release job which is why I raised the ticket.

**Comment by bmoscon** [comment]
@shashank88 looks fixed now!

**Comment by shashank88** [comment]
Thanks @bmoscon ! Will release 1.74 tomorrow morning

**Pull request merged**
