### PR TITLE
Tidy up logging

### PR DESCRIPTION
**Pull request by eeaston**
Makes the library a bit more downstream-user friendly wrt the use of logging - basically removes the singleton logger and only calls logging.basicConfig for the console scripts.
Also a bunch of little PEP8 fixes.

### CODE REVIEW

**Comment by Wilfred** [comment]
Looks good to me. :+1: 

If possible, please keep PEP8ification in a separate commit to functionality changes -- it makes changes easier to understand, especially if using git-bisect.

**Comment by jamesblackburn** [comment]
Looks great, thanks!

Is it possible to configure the logging level for the whole arctic library in one place, or does it get configured module by module now?

**Comment by eeaston** [comment]
@Wilfred - agreed, will separate them out for clarity
@jamesblackburn  - yes, having logging namespaces (created by the 'logger = logging.getLogger(__name__)' where __name__ is 'arctic.x.y'  means that you can set up the whole package's logging with a qualname of 'arctic'.

**Comment by jamesblackburn** [comment]
great, thanks @eeaston

**Pull request merged**
