### PR TITLE
fix failing integration tests on travis due to list_collection_names deprecation

### PR DESCRIPTION
**Pull request by dimosped**
Fixes issues #596 and #599

list_collection_names was added with pymongo 3.6.0:
https://github.com/mongodb/mongo-python-driver/blob/3.6.0/pymongo/database.py#L590

We switched to requiring pymongo>=3.6.0 recently:
https://github.com/manahl/arctic/blob/master/setup.py#L86

Therefore it is safe to simply replace collection_names with list_collection_names

### CODE REVIEW

**Comment by dimosped** [comment]
@bmoscon and @jamesblackburn  I added my self in the list of the contributors if you don't mind.

**Comment by dimosped** [comment]
@bmoscon  oh no!
More deprecation errors, fixing this as well
```
DeprecationWarning: count is deprecated. Use Collection.count_documents instead.
```

**Comment by dimosped** [comment]
instead of calling count() on the cursor, we now have to wall count_documents() on the collection, as a separate query.
http://api.mongodb.com/python/current/api/pymongo/cursor.html#pymongo.cursor.Cursor.count

The count_documents() was introduced in pymongo 3.7 and count() on the cursor was deprecated also at the same time.
http://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.count_documents

The options were:
1. Change our codebase to use count_documents(), forcing also setup.py to pymongo>=3.7 Unfortunately this would require a lot of code changes at the moment, as count() is all over the place in our home-brew projects.
2. Change our travis now to 3.6.0 <=pymongo<= 3.6.1 (code will still be compatible with 3.7 but with warning messages). No testing for 3.7, no detected breakages which is not great.
3. Change our setup.py to 3.6.0 <=pymongo<= 3.6.1, which is quite sad.

**Chosen solution**:
For now I have added a compatibility mode which makes things work with all pymongo versions, avoiding also the warning messages.

Later when 3.7+ will become the norm, we can drop support for <=3.6.1 and switch to using exclusively count_documents().

**Comment by dimosped** [comment]
@bmoscon  @jamesblackburn  please review the last commit and see my comment above, as this is blocking us.

**Comment by bmoscon** [comment]
looks good @dimosped

**Comment by dimosped** [comment]
This now fixes also #599, had to slightly modify a few of our fixtures.

Also changed the fix for #597 using a solution which avoids any import-time logic, and on first use of count() will lazily detect the right API.

**Comment by dimosped** [comment]
@bmoscon  feel free to have another look as I had to change quite a few things to make it work for:
 - python 3.
 - pytest 3.7.3
 - pymongo 3.7++
 - maintain backwards cocmpatiblility

I won't merge until we have both python 2+3 green on Travis and Green Circle CI.

**Comment by bmoscon** [comment]
@dimosped looks good, and travis and circle are both green now! (circle only failed on coveralls, since you're on a fork not a branch)

**Comment by dimosped** [comment]
thanks @bmoscon  merging now

**Pull request merged**
