### PR TITLE
Should check tz metadata for None for backward compatibility. Fixes #81

### LINKED ISSUE #81: Need to check that metadata exists before enumerating
https://github.com/manahl/arctic/commit/702ac62789642b159f03382a4a7246be0c1cd039

(see _pandas_ndarray_store.py, line 75)

Should check that recarr.dtype.metadata.get('index_tz') is not None before enumerating to avoid the error "TypeError: 'NoneType' object is not iterable"

### PR DESCRIPTION
**Pull request by AdrianTeng**
@jamesblackburn @bmoscon

### CODE REVIEW

**Comment by bmoscon** [comment]
Looks good, nice test.

**Comment by jamesblackburn** [comment]
LGTM!

**Comment by bmoscon** [comment]
Ah, ahl.pandas ?  :)

**Comment by AdrianTeng** [comment]
doh! Should use equal for index. Fixed

**Pull request merged**
